### PR TITLE
Remove YUI Compressor and use plain JavaScript

### PR DESCRIPTION
**Pull request by argilo**
This is a port of https://github.com/projecthorus/sondehub-tracker/pull/341.

So far I have only performed cursory testing. Someone more familiar with the project should probably have a closer look before merging this.

### CODE REVIEW

**Comment by argilo** [comment]
Hold off on merging this for now, since I'll need to pull in https://github.com/projecthorus/sondehub-tracker/pull/353 as well, once it's reviewed.

**Comment by argilo** [comment]
I've now incorporated https://github.com/projecthorus/sondehub-tracker/pull/353 and https://github.com/projecthorus/sondehub-tracker/pull/356 here as well.

**Review by TheSkorm — APPROVED** [review]

**Comment by darksidelemm** [comment]
Hmm, did I merge things in the wrong order?

**Comment by argilo** [comment]
No, a couple of the pull requests touched the same files, so conflicts were inevitable.

I rebased this one to resolve the conflict.

**Pull request merged**
